server:
  port: 8085
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: &connectionUrl jdbc:mysql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:3307}/mytapaz?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: &username ${DB_CONNECTION_USERNAME:root}
    password: &password ${DB_CONNECTION_PASSWORD:mysecretpassword}
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
#    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml

client:
  ms-birbank:
    endpoint: http://localhost:8080